# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false
deploy:
  skip_cleanup: true
  - provider: heroku
  api_key: "586e7d22-151b-4b46-b20a-48edf2a7ada5"