version: "3"

networks:
    nginx.docker:
      name: nginx.docker
      external: true

services:
# ----------------------  Nginx Gateway-------------------
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx/default.conf : /etc/nginx/conf.d/default.conf
      - nginx/certs : /etc/ssl/
      - nginx/index.html : /usr/share/nginx/html/index.html   
    networks:
      - nginx.docker
# ----------------------  XS2A Service ------------------- 
  xs2a-service:
    image: xs2a-service
    container_name: xs2a-service
    networks:
      - nginx.docker  
